# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks

repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
    - id: trailing-whitespace
    - id: end-of-file-fixer
    - id: check-yaml
    - id: check-json

  - repo: https://gitlab.com/daverona/pre-commit/cpp
    rev: 0.8.0                 # use the most recent version
    hooks:
    - id: clang-format         # formatter for C/C++ code based on a style guide
    - id: cpplint              # linter (or style-error checker) for Google C++ Style Guide
    - id: cppcheck             # static analyzer for C/C++ code
