# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks

repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
    - id: trailing-whitespace
    - id: end-of-file-fixer
    - id: check-yaml
    - id: check-json
  
  - repo: https://gitlab.com/daverona/pre-commit/cpp
    rev: 0.8.0                 # use the most recent version
    hooks:
    - id: docker-clang-format  # clang-format in Docker container
    - id: docker-cpplint       # cpplint in Docker container
    - id: docker-cppcheck      # cppcheck in Docker container
