name: release

on:
  release:
    created:

jobs:
  Doxygen:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Add version to doxyfile
      run: echo "PROJECT_NUMBER = $(git describe --tags --abbrev=0 | cut -c2-)" >> Doxyfile
    - name: Run Doxygen
      uses: mattnotmitt/doxygen-action@v1
    - uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./docs

  PlatformIO:
    runs-on: ubuntu-latest
    steps:
    - uses: bojit/platformio-publish@main
      with:
        token: ${{ secrets.PLATFORMIO_TOKEN }}
